; PlatformIO config for Cooler Light-API
; برای ساخت با هر برد خط مورد نظر را uncomment کنید.

[platformio]
default_envs = esp32dev
src_dir = .

[env]
monitor_speed = 115200
lib_deps = bblanchon/ArduinoJson@^6.21.0
build_flags = -DCORE_DEBUG_LEVEL=0

; -------- ESP32 --------
[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

[env:esp32-wroom]
platform = espressif32
board = esp32dev
framework = arduino

; -------- ESP8266 --------
[env:esp12e]
platform = espressif8266
board = esp12e
framework = arduino
board_build.filesystem = littlefs

[env:d1_mini]
platform = espressif8266
board = d1_mini
framework = arduino
board_build.filesystem = littlefs

[env:esp01_1m]
platform = espressif8266
board = esp01_1m
framework = arduino
board_build.filesystem = littlefs
